### ISSUE TITLE
Resolve deprecation warnings

### ISSUE THREAD

**Issue by inanimatt** [aerialship/SamlSPBundle#101]
When we use SamlSPBundle on Symfony 2.7, we get a number of deprecation warnings. Most of them appear to simply be through the use of the `security.context` service, instead of the `security.token_storage` and `security.authorization_checker` services introduced in Symfony 2.6, so resolving them should be straightforward. I can produce a PR if requested. Otherwise the changes required (that I've found) are:

Use `security.token_storage` instead of `security.context`:

* `src/AerialShip/SamlSPBundle/Bridge/LogoutReceiveResponse.php`
* `src/AerialShip/SamlSPBundle/Bridge/LogoutSendRequest.php`
* `src/AerialShip/SamlSPBundle/Bridge/SSOSessionCheck.php`

Replace `$this->getRequest()` with a type-hint in the action method definition in:

* `src/AerialShip/SamlSPBundle/Controller/SecurityController.php` line 44. 

This last one is just a matter of changing the method to something like this:

```php
use Symfony\Component\HttpFoundation\Request;
// …
    public function failureAction(Request $request)
    {
        /** @var $error AuthenticationException */
        $error = $request->getSession()->get(SecurityContextInterface::AUTHENTICATION_ERROR);
        return $this->render('AerialShipSamlSPBundle::failure.html.twig', array('error'=>$error));
    }
```

Obviously this would mean that the next release of SamlSPBundle will require Symfony 2.6 as a minimum, which may be a problem with some users (Symfony 2.3 support expires in May 2016). It may be worth adding a note to this effect in the README.

**Comment by tmilos** [comment]
@inanimatt a new version of lightsaml is available in it's own organization https://github.com/lightsaml/ and [sp bundle](https://github.com/lightSAML/SpBundle) supports symfony 2.3 - 3.0. This old aerialship/lightsaml version will not be upgraded to support v3.
