### ISSUE TITLE
status code responder

### ISSUE THREAD

**Issue by anthonyav** [aerialship/SamlSPBundle#103]
Hello,

I installed your bundle. When i try the connexion i have this error : 
Unsuccessful SAML response: urn:oasis:names:tc:SAML:2.0:status:Responder

How can i print the decode response from the idp in your bundle?

Sorry about this short message, but i don't really know what information i have to give you. So ask we what you need.

Thanks

**Comment by i3or1s** [comment]
Hi,
you can find what you need in the ```AerialShip/SamlSPBundle/Bridge``` namespace.

**Comment by anthonyav** [comment]
thanks
