### ISSUE TITLE
nameIdFormat and nameId

### ISSUE THREAD

**Issue by anthonyav** [aerialship/SamlSPBundle#104]
Hello,

i would like to know what is the purpose of NameId and NameIdFormat, because the idp by default doesn't give any value.
So i put as name_id_format in the config file security.yml :
name_id_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" 

but after i have an error "Call to a member function getValue() on null"
```
protected function createSSOState(ServiceInfo $serviceInfo, Assertion $assertion)
    {
        $ssoState = $this->ssoStore->create();
        //problem at this line
        $ssoState->setNameID($assertion->getSubject()->getNameID()->getValue());
        $ssoState->setNameIDFormat($assertion->getSubject()->getNameID()->getFormat() ?: '');
        $ssoState->setAuthenticationServiceName($serviceInfo->getAuthenticationService());
        $ssoState->setProviderID($serviceInfo->getProviderID());
        $ssoState->setSessionIndex($assertion->getAuthnStatement()->getSessionIndex());
        $this->ssoStore->set($ssoState);

        return $ssoState;
    }
```
thanks

**Comment by tmilos** [comment]
NameID is the term in SAML used as an identifier of the SSO session bearer and is necessary for the SLO. Unfortunately this bundle requires NameID, though it has faulty implemented SLO. Note there's a new version of lightsaml in it's own organization and bundle in https://github.com/lightSAML/SpBundle which does not require NameID. This old version will not be upgraded with new features any more.
