### ISSUE TITLE
Template error: "Unknown "dump" function in "AerialShipSamlSPBundle::failure.html.twig" at line 7."

### ISSUE THREAD

**Issue by osavchenko** [aerialship/SamlSPBundle#108]
I run my application in production mode but I got in error log such error:
```
request.CRITICAL: Uncaught PHP Exception Twig_Error_Syntax: "Unknown "dump" function in "AerialShipSamlSPBundle::failure.html.twig" at line 7." at /path/to/app/vendor/twig/twig/lib/Twig/ExpressionParser.php line 573 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"dump\" function in \"AerialShipSamlSPBundle::failure.html.twig\" at line 7. at /path/to/app/vendor/twig/twig/lib/Twig/ExpressionParser.php:573)"} []
```
This error is connected with [this line](https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Resources/views/failure.html.twig#L7).
Environment:
* Symfony 2.7
* saml-sp-bundle: 1.1.0

In dev environment all works well. Maybe we can avoid `dump` function and use something different?

**Comment by i3or1s** [comment]
this looks like a trailing error. I agree dump should not be there even if it is dev environment.

**Comment by osavchenko** [comment]
So, I can (and want) change it to something better, but I don't know what will be better in this case. Could you advice?

**Comment by i3or1s** [comment]
this shows up on `AuthenticationException`. I am still confused that it shows up in prod env since it is clearly happening only in dev `{% if app.environment == 'dev' %}`.
There is already a stack-trace `{{ error.getTraceAsString() }}` so just remove the line, there is no point in printing object out.

More serious question is how did this line got into prod log.

**Comment by i3or1s** [comment]
Please also check the new version.
New version of this library is in own organization: [lightsaml/sp-bundle](https://github.com/lightSAML/SpBundle). More details on [LightSAML website](http://www.lightsaml.com/SP-Bundle/).

**Comment by osavchenko** [comment]
Thank you! New version is compatible with this one?

**Comment by tmilos** [comment]
New version is SAML 2.0 compatible just as this one, but the configuration of the bundle is not the same, and it has many new features, SAML SSO SP profile is moved to [lightsaml/lightsaml](https://github.com/lightsaml/lightsaml) core library together with core data models, then there's separate [Symfony bridge bundle](https://github.com/lightSAML/SymfonyBridgeBundle), and finally there's [SP Bundle](https://github.com/lightSAML/SpBundle) that depends on those two. Generally, think it's more simple now.  Take a look at [SAML Symfony Bundle getting started](http://www.lightsaml.com/SP-Bundle/Getting-started/)

Regarding this issue, have removed stack trace print and dump function usage in PR #112

**Comment by osavchenko** [comment]
Thank you
