### ISSUE TITLE
checkPreAuth and create_user_if_not_exists

### ISSUE THREAD

**Issue by alex-ception** [aerialship/SamlSPBundle#43]
Hi,

I am using SamlSPBundle with FOSUserBundle with the option create_user_if_not_exists to true.

My workflow is : a new user has been authorized by the IDP and created in database with a flag "enabled" set to false. And since this flag is set to false, I don't want them to be able to log on my application.

I tried to put that logic in a custom UserProvider implementing UserManagerInterface, in createUserFromSamlInfo. Nevertheless, if I call a checkPreAuth here, the user is not returned, and the user is not created in database.

I don't know how to resolve my problem, nor where to call the checkPreAuth only at user creation.

Any ideas ?
Best regards,
Alexandre.

**Comment by tmilos** [comment]
I see several options you have

1) In ``UserManagerInterface::createUserFromSamlInfo()`` you could create a user in your db and throw ``UsernameNotFoundException`` to prevent him logging in

2) Your user class can implement ``Symfony\Component\Security\Core\User\AdvancedUserInterface`` and in your ``UserManagerInterface`` you create the new user and return it, and later on in [SamlSpAuthenticationProvider](https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Security/Core/Authentication/Provider/SamlSpAuthenticationProvider.php#L121) ``UserCheckerInterface::checkPostAuth`` will be called on your user, so in user class your ``isCredentialsNonExpired()`` method would have to return false to prevent login

It seems ``UserCheckerInterface::checkPreAuth`` is not called, so unfortunetly atm as bundle is, you can not rely on ``$user->isEnabled()``, but feel free to make a PR for it

BTW a new version of LightSAML is available in https://github.com/lightsaml/lightsaml with a Symfony bundle in https://github.com/lightSAML/SpBundle
