### ISSUE TITLE
Simulate authentication in functional test

### ISSUE THREAD

**Issue by Jeremlicious** [aerialship/SamlSPBundle#54]
Hi, I implemented SamlSPBundle in my service provider. Cool stuff it does the SSO job.
However all my functional test suite with Behat breaks in my SPsince the user can't get authenticated (I don't want the tests to need the IDP)

I implemented this official workaround and added a form_login firewall in security.yml but I'd rather using one firewall
http://symfony.com/doc/current/cookbook/testing/simulating_authentication.html

Is there anyway to create a cookie that will make SamlSPBundle authenticate a user in a future request ?

**Comment by tmilos** [comment]
This bundle uses [SamlSpToken](https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Security/Core/Authentication/Token/SamlSpToken.php), which is created by [SamlSpAuthenticationProvider](https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Security/Core/Authentication/Provider/SamlSpAuthenticationProvider.php#L124), so the code from [symfony simulating authentication](http://symfony.com/doc/current/cookbook/testing/simulating_authentication.html) will look something like this

``` php
// ...
private function logIn(UserInterface $user)
{
    $session = $this->client->getContainer()->get('session');

    $firewall = 'secured_area';
    $token = new SamlSpToken($firewall, array('ROLE_ADMIN'));
    $token->setUser($user);
    $session->set('_security_'.$firewall, serialize($token));
    $session->save();

    $cookie = new Cookie($session->getName(), $session->getId());
    $this->client->getCookieJar()->set($cookie);
}
// ...
```
