### ISSUE TITLE
Question:  Identity Provider Initiated

### ISSUE THREAD

**Issue by kwrjcr** [aerialship/SamlSPBundle#63]
I am wondering if SamlSPBundle supports "Identity Provider Initiated" and if so what changes to the docs for setup are needed if any?

**Comment by tmilos** [comment]
Think there should be no problems to receive IDP initiated SAML Response. In [AssertionConsumer](https://github.com/aerialship/SamlSPBundle/blob/master/src/AerialShip/SamlSPBundle/Bridge/AssertionConsumer.php#L156), handing the received Response, if field InReponseTo is empty then no validation if the AuthnRequest was made will be performed.
