### ISSUE TITLE
Enhancement - Refactor doctrine mongodb-odm support. 

### ISSUE THREAD

**Issue by BernardoSilva** [aerialship/SamlSPBundle#80]
Nice suggestion from @fnash :
Quote from @fnash in https://github.com/aerialship/SamlSPBundle/pull/71#issuecomment-94787844
Move the `StateStoreManager` outside the Entity/ directory.

I also suggest that the mongo driver being named mongodb.yml than odm.yml, following fos user bundle db_driver config.

I suggest move `Entity\StateStoreManager` to `State\SSO\StateStoreManager`.
This may cause compatibility issues, will require to bump version.

**Comment by tmilos** [comment]
BC can be avoided by keeping empty ``Entity\SSOStateStoreManager`` extending ``State\SSO\SSOStateStoreManager`` and marked as deprecated.

**Comment by tmilos** [comment]
Implemented and merged by #83
