### ISSUE TITLE
Refactor to fos user bundle approach.

### ISSUE THREAD

**Issue by BernardoSilva** [aerialship/SamlSPBundle#81]
- [x] Create root folder Doctrine
 - [x] Move SSO StateStoreManager to `src/AerialShip/SamlSPBundle/Doctrine/StateStoreManager.php`
 - [x] Move SSOStateDocument to `src/AerialShip/SamlSPBundle/Doctrine/MongoDB/Document/SSOStateDocument.php`
 - [x] Rename `SSOStateDocument` to `SSOState` since its inside mongodb/document folder/namespace. 
 - [x] Move `SSOStateEntity` to `../Doctrine/Orm/Entity/SSOStateEntity.php`
 - [x] Rename `SSOStateEntity` to `SSOState` since its inside orm/entity folder/namespace.

This is inspered on https://github.com/FriendsOfSymfony/FOSUserBundle/tree/master/Doctrine suggested by @stof on https://github.com/aerialship/SamlSPBundle/pull/71#issuecomment-95113848

**Comment by stof** [comment]
The SSOStateEntity should **not** be in the Doctrine namespace: it is not tied to the Doctrine ORM at all. And there should be no SSOStateDocument at all. The same class should be used.

**Comment by BernardoSilva** [comment]
I think you can close this ticket as well @tmilos .
With mongoDB PR we ended up refactoring the whole bundle :p
