### ISSUE TITLE
Using entity_id instead of file for IdP

### ISSUE THREAD

**Issue by dialogik** [aerialship/SamlSPBundle#99]
I'm trying to use an Entity ID (URL) instead of a local file for the IdP Metadata

    security:
        ...
        firewalls:
            saml:
                pattern: ^/
                anonymous: true
                aerial_ship_saml_sp:
                    local_logout_path: /logout
                    provider: in_memory
                    services:
                        my_name:
                            idp:
                                entity_id: https://my-url.to/metadata
                            sp:
                                config:
                                    entity_id: ...

But I do get this error

    Warning: DOMDocument::load(): Empty string supplied as input

What is the proper way to include the metadata via URL?

**Comment by tmilos** [comment]
Loading IDP metadata from url is not supported atm by this bundle.

**Comment by dialogik** [comment]
Oh, that's a big miss.
